name: CI

# Controls when the workflow will run on pushs
on:
  # Triggers the workflow on push or pull request events but only for the main branch 
  push:
    branches: 
      - three
jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout other repository
      uses: actions/checkout@v2
      with:
        repository: dhivya3107/repo2
        ref: main
        path: 'dhivya3107/repo2'

    - name: Check for changes
      id: check-changes
      run: |
        cd dhivya3107/repo2
        git fetch origin
        if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
          echo "Changes detected!"
          echo "::set-output name=changes::true"
        else
          echo "No changes."
          echo "::set-output name=changes::false"
        fi

    - name: Notify changes
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        echo "Changes detected, notifying..."
        # Add your notification steps here
